// src/env.ts

// Simple environment variable access without validation
export const env = {
  // Authentication
  REBIZ_APP_AUTH_GOOGLE_ID: process.env.REBIZ_APP_AUTH_GOOGLE_ID,
  REBIZ_APP_AUTH_GOOGLE_SECRET: process.env.REBIZ_APP_AUTH_GOOGLE_SECRET,
  ENABLED_LOGIN_DOMAINS_REGEX: process.env.ENABLED_LOGIN_DOMAINS_REGEX,
  NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,

  // APIs
  EMAIL_API_KEY: process.env.EMAIL_API_KEY,
  WEATHER_API_KEY: process.env.WEATHER_API_KEY,
  NOVU_API_KEY: process.env.NOVU_API_KEY,

  // Database
  POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD,
  POSTGRES_USER: process.env.POSTGRES_USER,
  POSTGRES_DATABASE: process.env.POSTGRES_DATABASE,
  CLOUD_SQL_CONNECTION_NAME: process.env.CLOUD_SQL_CONNECTION_NAME,

  // Zeebe/Zeeqs
  ZEEBE_GATEWAY_URL: process.env.ZEEBE_GATEWAY_URL,
  ZEEBE_LOG_LEBEL: process.env.ZEEBE_LOG_LEBEL,
  ZEEBE_MAX_RETRIES: process.env.ZEEBE_MAX_RETRIES ? parseInt(process.env.ZEEBE_MAX_RETRIES, 10) : undefined,

  // Files upload
  REBIZ_APP_BUCKET_EMAIL: process.env.REBIZ_APP_BUCKET_EMAIL,
  REBIZ_APP_BUCKET_SECRET: process.env.REBIZ_APP_BUCKET_SECRET,
  REBIZ_APP_BUCKET_NAME: process.env.REBIZ_APP_BUCKET_NAME,
  REBIZ_APP_PROJECT_ID: process.env.REBIZ_APP_PROJECT_ID,

  // Sentry
  NEXT_ENABLE_SENTRY_LOGS: process.env.NEXT_ENABLE_SENTRY_LOGS,
  NEXT_SENTRY_DSN: process.env.NEXT_SENTRY_DSN,

  // NodeJs
  NEXT_RUNTIME: process.env.NEXT_RUNTIME,

  // Client-side only variables
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  NEXT_PUBLIC_API_INTERNAL_BASE: process.env.NEXT_PUBLIC_API_INTERNAL_BASE,
  NEXT_PUBLIC_LOG_LEVEL: process.env.NEXT_PUBLIC_LOG_LEVEL,
  NEXT_PUBLIC_ENABLE_PERMIT_ACCESS_LOGS: process.env.NEXT_PUBLIC_ENABLE_PERMIT_ACCESS_LOGS,
  NEXT_PUBLIC_ENABLE_E2E: process.env.NEXT_PUBLIC_ENABLE_E2E,
  NEXT_PUBLIC_APP_TITLE: process.env.NEXT_PUBLIC_APP_TITLE,
  NEXT_PUBLIC_LOGO_IMAGE: process.env.NEXT_PUBLIC_LOGO_IMAGE,
  NEXT_PUBLIC_MAP_API_KEY: process.env.NEXT_PUBLIC_MAP_API_KEY,
  NEXT_PUBLIC_MAP_MAP_ID: process.env.NEXT_PUBLIC_MAP_MAP_ID,
  NEXT_PUBLIC_NOVU_APP_ID: process.env.NEXT_PUBLIC_NOVU_APP_ID,
  NEXT_PUBLIC_NOVU_API: process.env.NEXT_PUBLIC_NOVU_API,
  NEXT_PUBLIC_NOVU_WS: process.env.NEXT_PUBLIC_NOVU_WS,
  NEXT_PUBLIC_NEXTAUTH_BASEPATH: process.env.NEXT_PUBLIC_NEXTAUTH_BASEPATH,
  NEXT_PUBLIC_ZEEBE_PLAY_BASE: process.env.NEXT_PUBLIC_ZEEBE_PLAY_BASEPATH,
  NEXT_PUBLIC_GRAPHQL_URL: process.env.NEXT_PUBLIC_GRAPHQL_URL,
  NEXT_PUBLIC_WEBSOCKET_URL: process.env.NEXT_PUBLIC_WEBSOCKET_URL,
  NEXT_PUBLIC_APP_VERSION: process.env.NEXT_PUBLIC_APP_VERSION,
};
